# 1. Assessor and analyst work

## 1.0. Rating and criteria

Please [open this document](https://static.googleusercontent.com/media/guidelines.raterhub.com/en//searchqualityevaluatorguidelines.pdf)
and study chapters 13.0-13.4. Your task will be to assess the organic answers of search engines given the same query.

## 1.1. Explore the page

For the following search engines:
- https://duckduckgo.com/
- https://www.bing.com/
- https://ya.ru/
- https://www.google.com/

Perform the same query: "**How to get from Kazan to Voronezh**".

Discuss with your TA the following:
1. Which elements you may identify at SERP? Ads, snippets, blends from other sources, ...?
2. Where are organic results? How many of them are there?

## 1.2. Rate the results of the search engine

If there are many of you in the group, assess all search engines, otherwise choose 1 or 2. There should be no less than 5 of your for each search engine. Use the scale from the handbook, use 0..4 numerical equivalents for `[FailsM, SM, MM, HM, FullyM]`. 

Compute:
- average relevance and standard deviation for each SERP element.
- [Fleiss kappa score](https://en.wikipedia.org/wiki/Fleiss%27_kappa#Worked_example) for your group. Use [this implementation](https://www.statsmodels.org/dev/generated/statsmodels.stats.inter_rater.fleiss_kappa.html).
- [Kendall rank coefficient](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient) for some pairs in your group. Use [this implementation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kendalltau.html).

Discuss numerical results. Did you agree on the relevance? Did you agree on the rank? What is the difference?

In [ ]:
import numpy as np
# example input by users
ranking_data = np.array([
    [4, 3, 4, 0, 1, 1, 1, 0, 1, 1, 1, 0], # assessor 1 relevance
    [4, 3, 3, 0, 2, 1, 1, 1, 2, 1, 1, 1], # 2
    [4, 4, 3, 4, 4, 3, 3, 3, 2, 2, 2, 2],
    [4, 4, 4, 4, 2, 3, 3, 2, 3, 3, 3, 1],
    [4, 4, 4, 4, 2, 2, 2, 4, 2, 2, 2, 3],
    [3, 3, 3, 3, 2, 2, 2, 3, 2, 2, 2, 3],
    [1, 4, 4, 1, 2, 2, 2, 1, 2, 2, 2, 0],
    [1, 3, 4, 4, 2, 2, 2, 2, 2, 1, 1, 1],
    [4, 3, 4, 3, 3, 2, 2, 2, 1, 0, 1, 0],
    [3, 3, 4 ,3, 4, 3 ,4 ,3 ,2, 4 ,2, 0],
    [1, 4, 4, 1, 1, 2, 2, 1, 2, 2, 2, 0],
    [1, 4, 3, 1, 4, 3, 1, 3, 3, 3, 3, 2]
    
])

Averages ang standard deviations per item.

In [ ]:
mean = np.mean(ranking_data, axis=0)
stddev = np.std(ranking_data, axis=0)

for i, (m, s) in enumerate(zip(mean, stddev)):
  print(f"{i+1} relevance {m:.2f} += {s:.2f}")

1 relevance 2.83 += 1.34
2 relevance 3.50 += 0.50
3 relevance 3.67 += 0.47
4 relevance 2.33 += 1.55
5 relevance 2.42 += 1.04
6 relevance 2.17 += 0.69
7 relevance 2.08 += 0.86
8 relevance 2.08 += 1.11
9 relevance 2.00 += 0.58
10 relevance 1.92 += 1.04
11 relevance 1.83 += 0.69
12 relevance 1.08 += 1.11


Fleiss kappa score

In [ ]:
!pip install statsmodels

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from statsmodels.stats.inter_rater import aggregate_raters, fleiss_kappa

# TODO your code here
agg, cats =  aggregate_raters(ranking_data.T)
print(agg)
fleiss_kappa(agg)

[[0 4 0 2 6]
 [0 0 0 6 6]
 [0 0 0 4 8]
 [2 3 0 3 4]
 [0 2 6 1 3]
 [0 2 6 4 0]
 [0 3 6 2 1]
 [1 3 3 4 1]
 [0 2 8 2 0]
 [1 3 5 2 1]
 [0 4 6 2 0]
 [5 3 2 2 0]]


0.11603214841929356

Kendall tau score is pairwise. Compare one to another.

In [ ]:
corrs = np.zeros_like(ranking_data)


In [ ]:
from scipy.stats import kendalltau

# TODO your code here
# np.zeros()


for i, _ in enumerate(ranking_data):
  for j, _ in enumerate(ranking_data):
    if i != j:
      corr = kendalltau(ranking_data[i, :], ranking_data[j,:])
      corrs[i,j] = corr.correlation
  
corrs

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# 2. Engineer work

You will create a bucket of URLs which are relevant for the query **"free cloud git"**. Then you will automate the search procedure using https://serpapi.com/, or https://developers.google.com/custom-search/v1/overview, or whatever.

Then you will compute MRR@10 and Precision@10.

## 2.1. Build your bucket here

In [ ]:
rel_bucket = [
    "github.com",
    "gitpod.io",
    "gitflic.ru",
    "git-scm.com",
    "gitlab.com",
    "git-tower.com",
    "azure.microsoft.com",
    "gitea.io",
]

query = "free git cloud"

## 2.2. Relevance assessment

Write the code to check that the obtained document is relevant (True) or not (False).

In [ ]:
def is_rel(resp_url):
    # TODO your code here
    return any(r in resp_url for r in rel_bucket)
    

## 2.3. Automation

Get search results from the automation tool you use.

In [ ]:
import json

with open('sample.json') as f:
  data = json.load(f)

In [ ]:
rels = []

for result in data["organic_results"]:
    print(f"pos: {result['position']}")
    print(f"title: {result['title']}")
    print(result['link'])
    print(is_rel(result['link']))
    rels.append(int(is_rel(result['link'])))
    print()

pos: 1
title: 6 places to host your git repository - Opensource.com
https://opensource.com/article/18/8/github-alternatives
False

pos: 2
title: Bitbucket | Git solution for teams using Jira
https://bitbucket.org/product
False

pos: 3
title: Gitpod: Always ready to code.
https://www.gitpod.io/
True

pos: 4
title: GitLab: The DevSecOps Platform
https://about.gitlab.com/
True

pos: 5
title: GitHub: Let's build from here · GitHub
https://github.com/
True

pos: 6
title: 14 Git Hosting Services Compared | Tower Blog
https://www.git-tower.com/blog/git-hosting-services-compared/
True

pos: 7
title: Top GitHub Alternatives to Host Your Open Source Projects
https://itsfoss.com/github-alternatives/
False

pos: 8
title: Git
https://git-scm.com/
True

pos: 9
title: Top 10 best Git hosting solutions and services in 2021
https://www.devopsschool.com/blog/top-5-git-hosting-solutions/
False

pos: 10
title: 15 Best Github Alternatives in 2023 - Guru99
https://www.guru99.com/github-alternative.html
Fals

In [ ]:
rels

[0, 0, 1, 1, 1, 1, 0, 1, 0, 0]

## 2.4. MRR

Compute MRR:

In [ ]:
def mrr(list_of_lists, k=10):
    # todo your code here

    score = 0
    for li in list_of_lists:
      if 1 not in li:
        score += 1/(k+1)
      else:
        score += 1/(li.index(1) + 1) 
    return score / len(list_of_lists)

In [ ]:
mrr([rels]) # BTW, why do I wrap the list into additional brackets? :)

0.3333333333333333

## 2.5. Precision
Compute mean precision:

In [ ]:
def mp(list_of_lists, k=10):
    # todo your code here
    p = 0
    for l in list_of_lists:
        p += sum(l) / k
    return p / len(list_of_lists)

In [ ]:
mp([rels])

0.5